baseURL = "http://skilldevelopers.com/"
languageCode = "en-us"
title = "SkillDevelopers.com"
theme = "skilldev"
disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS"]
[taxonomies]
  tag = ""
  group = ""
  category = ""